import {
  REVIEW_STATE_LABELS,
  type IntelligenceReviewState,
} from "@/components/identity-intelligence/types";
import { BRAND } from "@/lib/brand";

export function IdentityReviewStateLabel({
  state,
  label,
}: {
  state: IntelligenceReviewState;
  /** Optional card-specific label override. */
  label?: string;
}) {
  return (
    <span className="identity-review-state" data-state={state}>
      {label ?? REVIEW_STATE_LABELS[state]}
      <span className="sr-only">
        {state === "draft"
          ? `. Generated by ${BRAND.intelligenceName} and not yet reviewed.`
          : state === "reviewed"
            ? ". Opened or reviewed, but not accepted."
            : state === "accepted"
              ? ". Approved as a useful coaching insight."
              : ". Not accepted for future use."}
      </span>
    </span>
  );
}
